# ref: https://github.com/getsops/sops/blob/main/config/config.go

creation_rules:
  - path_regex: secrets.yaml$
    encrypted_regex: "(access_key|key_id)"
    age: >-
      age1kuk0xhyha5ecs4hfwu7htj7xkwsxjq70runwm9lmxq3z8gumxgwq4m74j2
