apiVersion: v1
kind: Pod
metadata:
  name: pod-reader
spec:
  terminationGracePeriodSeconds: 0
  serviceAccountName: pod-reader
  containers:
  - name: pod-reader
    image: ghcr.io/sfmunoz/k8s-bulk:v1.3.0
    imagePullPolicy: IfNotPresent
    command: ["python3","-u","-c"]
    args:
    - |
      from kubernetes import client, config
      from time import time,sleep
      #config.load_kube_config()
      config.load_incluster_config()
      api = client.CoreV1Api()
      while True:
          try:
              pods = api.list_namespaced_pod("rbac")
              for pod in pods.items:
                  print(time(),pod.metadata.name,"|",pod.status.phase,"|",pod.status.pod_ip)
              print(time(),"----")
          except Exception as e:
              print(time(),str(e))
          sleep(1)

