apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        command: ["/bin/bash","-c"]
        args:
          - "openssl rand -hex 4 > /usr/share/nginx/html/index.html ; exec /docker-entrypoint.sh nginx -g 'daemon off;'"
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "200m"
        ports:
          - containerPort: 80
