apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ include "pvName" . }}"
spec:
  capacity:
    storage: 10Gi # Ignored, required
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: "{{ .Release.Namespace }}" # Namespace is required even though it's in "default" namespace.
    name: {{ .Values.pvcName | quote }}
  mountOptions:
    - uid=70
    - gid=70
    - allow-other
    - allow-delete
    - {{ .Values.region | printf "region %s" | quote }}
    - {{ .Release.Namespace | printf "prefix %s/" | quote }}
  csi:
    driver: s3.csi.aws.com # Required
    volumeHandle: {{ printf "s3-vol-%s" .Release.Namespace | quote }}  # Must be unique
    volumeAttributes:
      bucketName: {{ .Values.bucket | quote }}
