apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "pvcName" . }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  resources:
    requests:
      storage: 10Gi # Ignored, required
  volumeName: "{{ include "pvName" . }}" # Name of your PV
