{{- if .Values.original.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3.fullname" . }}
  labels:
    {{- include "s3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "s3.selectorLabels" . | nindent 4 }}
{{- end }}
