apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
      - name: rclone
        image: {{ .Values.rclone.image }}
        command: ["/bin/sh","-c"]
        args:
        - |
          #!/bin/sh
          cp /usr/local/bin/rclone /shared/rclone
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: vol-shared
          mountPath: /shared
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        command: ["/bin/sh","-c"]
        args:
        - |
          set -x -e -o pipefail
          cp /shared/rclone /usr/local/bin/rclone
          chown 0:0 /usr/local/bin/rclone
          chmod 755 /usr/local/bin/rclone
          date
          FOLDER="$(rclone lsf rem: | sort -r | awk '/^bck-\d{8}-\d{6}\/$/ { print substr($1,1,19) ; exit 0 ; }')"
          date
          if [ "$FOLDER" != "" ]
          then
            mkdir -p "${PGDATA}"
            chown postgres:root "${PGDATA}"
            chmod 0700 "${PGDATA}"
            date
            rclone copyto -P "rem:${FOLDER}" "/loc/${FOLDER}"
            date
            tar -C "${PGDATA}" -xvzf "/loc/${FOLDER}/base.tar.gz"
            date
            tar -C "${PGDATA}/pg_wal" -xvzf "/loc/${FOLDER}/pg_wal.tar.gz"
            date
            rm -rf "/loc/${FOLDER}"
          fi
          date
          exec docker-entrypoint.sh postgres
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: vol-c
          mountPath: /root/.config/rclone
          readOnly: true
        - name: vol-c
          mountPath: /var/lib/postgresql/.config/rclone
          readOnly: true
        - name: vol-docker-entrypoint-initdb-d
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        - name: vol-shared
          mountPath: /shared
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: vol-c
        secret:
          secretName: postgres-rclone-conf
          items:
          - key: rcloneConf
            path: rclone.conf
      - name: vol-shared
        emptyDir: {}
      - name: vol-docker-entrypoint-initdb-d
        configMap:
          name: postgres-docker-entrypoint-initdb-d
