apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres-service
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
      - name: rclone
        image: {{ .Values.rclone.image }}
        command: ["/bin/sh","-c"]
        args:
        - |
          #!/bin/sh
          cp /usr/local/bin/rclone /shared/rclone
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: vol-shared
          mountPath: /shared
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        command: ["/bin/sh","-c"]
        args:
        - "exec /bin/sh /postgres-init/init.sh"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_PASSWORD
        - name: EMPTY
          value: {{ .Values.postgres.empty | ternary "yes" "no" | quote }}
        volumeMounts:
        - name: vol-c
          mountPath: /root/.config/rclone
          readOnly: true
        - name: vol-c
          mountPath: /var/lib/postgresql/.config/rclone
          readOnly: true
        - name: vol-postgres-init
          mountPath: /postgres-init
          readOnly: true
        - name: vol-docker-entrypoint-initdb-d
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        - name: vol-shared
          mountPath: /shared
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: vol-c
        secret:
          secretName: postgres-rclone-conf
          items:
          - key: rcloneConf
            path: rclone.conf
      - name: vol-postgres-init
        configMap:
          name: postgres-init
      - name: vol-docker-entrypoint-initdb-d
        configMap:
          name: postgres-docker-entrypoint-initdb-d
      - name: vol-shared
        emptyDir: {}
