apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-init
#immutable: true
data:
  init.sh: |
    #!/bin/sh
    for F in /rclone-conf/*
    do
      [ -f "$F" ] && export $(basename "$F")="$(cat "$F")"
    done
    mkdir -p /config/rclone
    cat << __EOF > /config/rclone/rclone.conf
    [s3]
    type = s3
    provider = AWS
    access_key_id = $MY_S3_ACCESS_KEY_ID
    secret_access_key = $MY_S3_SECRET_ACCESS_KEY
    region = $MY_S3_REGION
    location_constraint = $MY_S3_REGION

    [bck]
    type = alias
    remote = s3:$MY_S3_BUCKET/$MY_ENV
    __EOF
    chown 0:0 /config /config/rclone /config/rclone/rclone.conf
    chmod 700 /config /config/rclone
    chmod 600 /config/rclone/rclone.conf
    exec tail -f /dev/null
