apiVersion: apps/v1
kind: Deployment
metadata:
  name: rclone-deploy
  labels:
    app: rclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rclone
  template:
    metadata:
      labels:
        app: rclone
    spec:
      containers:
{{ include "rclone.container" ( dict "root" . "cmd" "/scripts/rclone.sh" "volumeNameConf" "vol-c" "volumeMounts" .Values.volumeMounts ) | indent 6 }}
      volumes:
{{ include "rclone.volumes" ( dict "root" . "volumeNameConf" "vol-c" "secretName" "rclone-conf" "secretKey" "rcloneConf" "volumes" .Values.volumes ) | indent 6 }}
