apiVersion: apps/v1
kind: Deployment
metadata:
  name: rclone-deploy
  labels:
    app: rclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rclone
  template:
    metadata:
      labels:
        app: rclone
    spec:
      containers:
{{ include "rclone.container" ( dict "root" . "volumeName" "rcvol" ) | indent 6 }}
      volumes:
{{ include "rclone.volume" ( dict "root" . "volumeName" "rcvol" "secretName" "rclone-conf" "secretKey" "rcloneConf" ) | indent 6 }}
