apiVersion: apps/v1
kind: Deployment
metadata:
  name: rclone-deploy
  labels:
    app: rclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rclone
  template:
    metadata:
      labels:
        app: rclone
    spec:
      containers:
{{ include "rclone.container" ( dict "root" . "cmd" "exec tail -f /dev/null" "volScripts" .Values.volScripts "volumeNameConf" "vol-c" "volumeNameBck" "vol-b" ) | indent 6 }}
      volumes:
{{ include "rclone.volume" ( dict "root" . "volumeNameConf" "vol-c" "volumeNameBck" "vol-b" "secretName" "rclone-conf" "secretKey" "rcloneConf" ) | indent 6 }}
