{{ $rcloneVars := set .Values.myCfg "S3_FOLDER" .Release.Namespace }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rclone-conf
data:
  rcloneConf: {{ include "rclone.conf" $rcloneVars | b64enc | quote }}
